- name: Copy K8s manifests
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{ item }}"
  with_items:
    - service.yaml
    - ingress.yaml
    - aws-secrets.yml

- name: Apply K8s manifests
  command: kubectl apply -f "/tmp/{{ item }}"
  with_items:
    - service.yaml
    - ingress.yaml
    - aws-secrets.yml

- name: Deploy WordPress with Helm
  command: >
    helm upgrade --install wordpress bitnami/wordpress
    --set mariadb.enabled=false
    --set externalDatabase.host={{ wordpress_db_host }}
    --set externalDatabase.user={{ wordpress_db_user }}
    --set externalDatabase.password={{ wordpress_db_password }}
    --set externalDatabase.database={{ wordpress_db_name }}
    --set service.type=NodePort
    --set service.nodePorts.http=30080
    --set wordpressHost={% if environment == 'prod' %}mmustar.fr{% else %}test.mmustar.fr{% endif %}