replicaCount: 1

image:
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: {{ .Values.env.domain }}
      paths:
        - path: /
          pathType: Prefix

database:
  secretName: wordpress-secrets  
  
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  domain: ""
