apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
data:
  MYSQL_DATABASE: {{ .Values.database.name | b64enc }}
  MYSQL_USER: {{ .Values.database.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.database.password | b64enc }}
  MYSQL_HOST: {{ .Values.database.host | b64enc }}
