# monitoring/ansible/inventory/hosts.yml
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    monitoring:
      children:
        test:
          hosts:
            monitoring-test:
              ansible_host: 35.180.222.29
              domain_name: test.mmustar.fr
              environment: test
        prod:
          hosts:
            monitoring-prod:
              ansible_host: 35.181.234.232
              domain_name: mmustar.fr
              environment: prod