---
- block:
    - name: Force kill any apt/dpkg processes
      shell: |
        killall apt apt-get dpkg 2>/dev/null || true
        rm -f /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock* 2>/dev/null || true
        dpkg --configure -a
      changed_when: false
      ignore_errors: true

    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_update
      retries: 3
      delay: 5
      until: apt_update is success

    - name: Install system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-boto3
          - python3-botocore
          - git
          - vim
        state: present
  become: true