- name: Update package cache
  apt:
    update_cache: yes
  become: yes

- name: Install system packages
  apt:
    name:
      - python3
      - python3-pip
      - git
      - vim
    state: present
  become: yes