# roles/common/handlers/main.yml
- name: Update package cache
  ansible.builtin.command: yum makecache
  become: yes

- name: Install python3-dnf
  ansible.builtin.command: yum install -y python3-dnf
  become: yes

- name: Install system packages
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
      - git
      - vim
    state: present
    update_cache: yes
    use_backend: dnf4
  become: yes
