---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - python3-setuptools
      - python3-apt
      - acl
      - git
    state: present

- name: Install required Python packages
  pip:
    name:
      - boto3
      - botocore
      - openshift
      - kubernetes
    state: present

- name: Set timezone
  timezone:
    name: UTC

- name: Create SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Upload SSL certificate
  copy:
    content: "{{ ssl_certificate }}"
    dest: "/etc/nginx/ssl/{{ domain_name }}.pem"
    mode: '0644'
  when: ssl_certificate is defined

- name: Upload SSL key
  copy:
    content: "{{ ssl_key }}"
    dest: "/etc/nginx/ssl/{{ domain_name }}.key"
    mode: '0600'
  when: ssl_key is defined

- name: Ensure AWS CLI is installed
  pip:
    name: awscli
    state: present