- name: Vérifier si le Secret existe
  command: kubectl get secret wordpress-secrets -n default
  register: secret_exists
  ignore_errors: true

- name: Créer ou mettre à jour le Secret Kubernetes
  shell: |
    kubectl delete secret wordpress-secrets -n default --ignore-not-found
    kubectl create secret generic wordpress-secrets -n default \
      --from-literal=MYSQL_USER={{ wp_db_user }} \
      --from-literal=MYSQL_PASSWORD={{ wp_db_password }} \
      --from-literal=MYSQL_DATABASE={{ wp_db_name }}
  when: secret_exists.rc != 0
