- name: Ajouter le repo Helm Bitnami
  command: helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Mettre à jour les dépôts Helm
  command: helm repo update

- name: Déployer WordPress avec Helm et CSI Driver
  command: >
    helm upgrade --install wordpress bitnami/wordpress
    --set mariadb.enabled=false
    --set externalDatabase.host={{ wordpress_db_host }}
    --set externalDatabase.user={{ wordpress_db_user }}
    --set externalDatabase.password={{ wordpress_db_password }}
    --set externalDatabase.database={{ wordpress_db_name }}
    --set persistence.enabled=true
    --set persistence.storageClass=aws-secrets
    --set extraVolumes[0].name=aws-secrets
    --set extraVolumes[0].csi.driver=secrets-store.csi.k8s.io
    --set extraVolumes[0].csi.readOnly=true
    --set extraVolumes[0].csi.volumeAttributes.secretProviderClass=wordpress-aws-secrets
    --set extraVolumeMounts[0].name=aws-secrets
    --set extraVolumeMounts[0].mountPath=/mnt/secrets-store
    --set extraVolumeMounts[0].readOnly=true
  args:
    chdir: /home/ubuntu/Documents/wp-projet/wordpress-infra
