- name: Ajouter le repo Helm Bitnami
  command: helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Mettre à jour les dépôts Helm
  command: helm repo update

- name: Déployer WordPress avec Helm et CSI Driver
  command: >
    helm upgrade --install wordpress bitnami/wordpress
    --set mariadb.enabled=false
    --set externalDatabase.host={{ wordpress_db_host }}
    --set externalDatabase.user={{ wordpress_db_user }}
    --set externalDatabase.password={{ wordpress_db_password }}
    --set externalDatabase.database={{ wordpress_db_name }}
    --set persistence.enabled=true
    --set service.type=NodePort
    --set service.nodePorts.http=30080
  args:
    chdir: /home/ubuntu/Documents/wp-projet/wordpress-infra
