---
- name: Installer Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Démarrer Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Lancer WordPress
  docker_container:
    name: wordpress
    image: wordpress:latest
    ports:
      - "80:80"
    env:
      WORDPRESS_DB_HOST: "{{ wordpress_db_host }}"
      WORDPRESS_DB_USER: "{{ wordpress_db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ wordpress_db_password }}"
      WORDPRESS_DB_NAME: "{{ wordpress_db_name }}"
    restart_policy: always