- name: Récupérer les secrets depuis AWS Secrets Manager
  shell: |
    aws secretsmanager get-secret-value --secret-id book --query SecretString --output text
  register: aws_secrets

- name: Stocker les credentials dans des variables
  set_fact:
    wp_db_user: "{{ aws_secrets.stdout | from_json | json_query('MYSQL_USER') }}"
    wp_db_password: "{{ aws_secrets.stdout | from_json | json_query('MYSQL_PASSWORD') }}"
    wp_db_name: "{{ aws_secrets.stdout | from_json | json_query('MYSQL_DATABASE') }}"
