---
- name: Inclure les tâches de récupération des secrets
  include_tasks: secrets.yml

- name: Créer le répertoire de données de WordPress
  file:
    path: "{{ wp_volume_path }}"
    state: directory
    mode: '0755'

- name: Générer le fichier wp-config.php depuis le template
  template:
    src: wp-config.php.j2
    dest: "{{ wp_volume_path }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Restart PHP-FPM

- name: Démarrer le conteneur WordPress
  community.docker.docker_container:
    name: wordpress
    image: "{{ wordpress_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ wordpress_port }}:80"
    env:
      WORDPRESS_DB_HOST: "{{ mysql_host }}:{{ mysql_port }}"
      WORDPRESS_DB_USER: "{{ mysql_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_password }}"
      WORDPRESS_DB_NAME: "{{ mysql_database }}"
      WP_ID: "{{ wp_id }}"
      AUTH_KEY: "{{ auth_key }}"
      SECURE_AUTH_KEY: "{{ secure_auth_key }}"
      LOGGED_IN_KEY: "{{ logged_in_key }}"
      NONCE_KEY: "{{ nonce_key }}"
      AUTH_SALT: "{{ auth_salt }}"
      SECURE_AUTH_SALT: "{{ secure_auth_salt }}"
      LOGGED_IN_SALT: "{{ logged_in_salt }}"
      NONCE_SALT: "{{ nonce_salt }}"
    volumes:
      - "{{ wp_volume_path }}:/var/www/html"
