---
- name: Include tasks to fetch secrets
  include_tasks: secrets.yml

- name: Create WordPress data directory
  file:
    path: "{{ wp_volume_path }}"
    state: directory
    mode: '0755'

- name: Start the WordPress container
  community.docker.docker_container:
    name: wordpress
    image: "{{ wordpress_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
    env:
      WORDPRESS_DB_HOST: "{{ wordpress_db_host }}"
      WORDPRESS_DB_USER: "{{ wordpress_db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ wordpress_db_password }}"
      WORDPRESS_DB_NAME: "{{ wordpress_db_name }}"
    volumes:
      - "{{ wp_volume_path }}:/var/www/html"

      #cool