---
- name: Create WordPress data directory
  file:
   path: "{{ wp_volume_path }}"
   state: directory
   mode: '0755'

- name: Get AWS secrets
  block:
   - name: Execute get_secret.py
     script: roles/common/files/get_secret.py
     register: secret_output
     delegate_to: localhost
     become: false
     changed_when: false

   - name: Parse JSON output and set WordPress variables
     set_fact:
       mysql_host: "{{ secret_output.stdout | from_json | json_query('MYSQL_HOST') }}" 
       mysql_user: "{{ secret_output.stdout | from_json | json_query('MYSQL_USER') }}"
       mysql_password: "{{ secret_output.stdout | from_json | json_query('MYSQL_PASSWORD') }}"
       mysql_database: "{{ secret_output.stdout | from_json | json_query('MYSQL_DATABASE') }}"
       mysql_port: "{{ secret_output.stdout | from_json | json_query('MYSQL_PORT') }}"
     no_log: true

- name: Create WordPress container
  community.docker.docker_container:
   name: wordpress
   image: "{{ wordpress_image }}"
   state: started
   restart_policy: always
   published_ports:
     - "{{ wordpress_port }}:80"
   env:
     WORDPRESS_DB_HOST: "{{ mysql_host }}:{{ mysql_port }}"
     WORDPRESS_DB_USER: "{{ mysql_user }}"
     WORDPRESS_DB_PASSWORD: "{{ mysql_password }}"
     WORDPRESS_DB_NAME: "{{ mysql_database }}"
   volumes:
     - "{{ wp_volume_path }}:/var/www/html"