# ansible/roles/wordpress/tasks/main.yml
---
- name: Include tasks to fetch secrets
  include_tasks: secrets.yml

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ wp_volume_path }}"
    - "/tmp/kubernetes"

- name: Copy Kubernetes manifests
  template:
    src: "{{ item }}"
    dest: "/tmp/kubernetes/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob:
    - "../templates/*.j2"

- name: Add Bitnami repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Deploy WordPress
  kubernetes.core.helm:
    name: wordpress
    chart_ref: bitnami/wordpress
    release_namespace: default
    create_namespace: true
    values:
      mariadb:
        enabled: false
      externalDatabase:
        host: "{{ wordpress_db_host }}"
        user: "{{ wordpress_db_user }}"
        password: "{{ wordpress_db_password }}"
        database: "{{ wordpress_db_name }}"
        port: 3306
      service:
        type: NodePort
        nodePorts:
          http: 30081  # Changé de 30080 à 30081
      persistence:
        enabled: true
        size: 10Gi
      wordpressHost: "{{ 'test.mmustar.fr' if environment == 'test' else 'mmustar.fr' }}"

- name: Apply additional manifests
  kubernetes.core.k8s:
    state: present
    src: "/tmp/kubernetes/{{ item }}"
  with_items:
    - ingress.yaml
    - aws-secrets.yml