---
- name: Include tasks to fetch secrets
  include_tasks: secrets.yml

- name: Create WordPress data directory
  file:
    path: "{{ wp_volume_path }}"
    state: directory
    mode: '0755'

- name: Generate wp-config.php from template
  template:
    src: wp-config.php.j2
    dest: "{{ wp_volume_path }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Restart PHP-FPM

- name: Start the WordPress container without environment variables
  community.docker.docker_container:
    name: wordpress
    image: "{{ wordpress_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ wordpress_port }}:80"
    volumes:
      - "{{ wp_volume_path }}:/var/www/html"
