---
- name: Récupérer les secrets depuis les variables d'environnement
  set_fact:
    mysql_host: "{{ lookup('env', 'WORDPRESS_DB_HOST') }}"
    mysql_user: "{{ lookup('env', 'WORDPRESS_DB_USER') }}"
    mysql_password: "{{ lookup('env', 'WORDPRESS_DB_PASSWORD') }}"
    mysql_database: "{{ lookup('env', 'WORDPRESS_DB_NAME') }}"
    mysql_port: "{{ lookup('env', 'MYSQL_PORT') }}"
    wp_id: "{{ lookup('env', 'WP_ID') }}"
    auth_key: "{{ lookup('env', 'AUTH_KEY') }}"
    secure_auth_key: "{{ lookup('env', 'SECURE_AUTH_KEY') }}"
    logged_in_key: "{{ lookup('env', 'LOGGED_IN_KEY') }}"
    nonce_key: "{{ lookup('env', 'NONCE_KEY') }}"
    auth_salt: "{{ lookup('env', 'AUTH_SALT') }}"
    secure_auth_salt: "{{ lookup('env', 'SECURE_AUTH_SALT') }}"
    logged_in_salt: "{{ lookup('env', 'LOGGED_IN_SALT') }}"
    nonce_salt: "{{ lookup('env', 'NONCE_SALT') }}"
  no_log: true
