---
- name: Vérifier si le fichier de secrets existe
  stat:
    path: "{{ secrets_file }}"
  register: secrets_file_check

- name: Échouer si le fichier de secrets n'existe pas
  fail:
    msg: "Le fichier {{ secrets_file }} est introuvable !"
  when: not secrets_file_check.stat.exists

- name: Lire le fichier secrets.json
  slurp:
    src: "{{ secrets_file }}"
  register: secrets_content

- name: Convertir JSON en variable Ansible
  set_fact:
    db_secrets: "{{ secrets_content.content | b64decode | from_json }}"
  no_log: true

- name: Définir les variables de WordPress
  set_fact:
    mysql_host: "{{ db_secrets.MYSQL_HOST }}"
    mysql_user: "{{ db_secrets.MYSQL_USER }}"
    mysql_password: "{{ db_secrets.MYSQL_PASSWORD }}"
    mysql_database: "{{ db_secrets.MYSQL_DATABASE }}"
    mysql_port: "{{ db_secrets.MYSQL_PORT }}"
    wp_id: "{{ db_secrets.WP_ID }}"
    auth_key: "{{ db_secrets.AUTH_KEY }}"
    secure_auth_key: "{{ db_secrets.SECURE_AUTH_KEY }}"
    logged_in_key: "{{ db_secrets.LOGGED_IN_KEY }}"
    nonce_key: "{{ db_secrets.NONCE_KEY }}"
    auth_salt: "{{ db_secrets.AUTH_SALT }}"
    secure_auth_salt: "{{ db_secrets.SECURE_AUTH_SALT }}"
    logged_in_salt: "{{ db_secrets.LOGGED_IN_SALT }}"
    nonce_salt: "{{ db_secrets.NONCE_SALT }}"
  no_log: true
