---
- name: Fetch AWS Secrets Manager values
  community.aws.aws_secret:
    name: "book"
    region: "{{ aws_region }}"
  register: secret_data

- name: Convert Secret Data to YAML
  set_fact:
    secret_values: "{{ secret_data.secret | from_json }}"

- name: Create temporary secrets file
  copy:
    content: "{{ secret_values | to_nice_yaml }}"
    dest: "/tmp/wordpress-secrets.yml"
    mode: '0600'
  delegate_to: localhost

- name: Load secrets into environment
  set_fact:
    mysql_host: "{{ secret_values.MYSQL_HOST }}"
    mysql_port: "{{ secret_values.MYSQL_PORT }}"
    mysql_database: "{{ secret_values.MYSQL_DATABASE }}"
    mysql_user: "{{ secret_values.MYSQL_USER }}"
    mysql_password: "{{ secret_values.MYSQL_PASSWORD }}"
    mysql_root_password: "{{ secret_values.MYSQL_ROOT_PASSWORD }}"
    wp_auth_key: "{{ secret_values.AUTH_KEY }}"
    wp_secure_auth_key: "{{ secret_values.SECURE_AUTH_KEY }}"
    wp_logged_in_key: "{{ secret_values.LOGGED_IN_KEY }}"
    wp_nonce_key: "{{ secret_values.NONCE_KEY }}"
    wp_auth_salt: "{{ secret_values.AUTH_SALT }}"
    wp_secure_auth_salt: "{{ secret_values.SECURE_AUTH_SALT }}"
    wp_logged_in_salt: "{{ secret_values.LOGGED_IN_SALT }}"
    wp_nonce_salt: "{{ secret_values.NONCE_SALT }}"
  no_log: true