# roles/wordpress/tasks/secrets.yml
---
- name: Get AWS secrets
  block:
    - name: Execute get_secret.py
      script: roles/common/files/get_secret.py
      register: secret_output
      delegate_to: localhost
      become: false
      changed_when: false

    - name: Parse JSON output
      set_fact:
        db_secrets: "{{ secret_output.stdout | from_json }}"
      no_log: true

    - name: Set database variables
      set_fact:
        db_host: "{{ db_secrets.MYSQL_HOST }}"
        db_name: "{{ db_secrets.MYSQL_DATABASE }}"
        db_user: "{{ db_secrets.MYSQL_USER }}"
        db_password: "{{ db_secrets.MYSQL_PASSWORD }}"
      no_log: true

# roles/wordpress/tasks/main.yml
---
- name: Include secrets tasks
  include_tasks: secrets.yml

- name: Create WordPress container
  community.docker.docker_container:
    name: wordpress
    image: "{{ wordpress_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ wordpress_port }}:80"
    env:
      WORDPRESS_DB_HOST: "{{ db_host }}"
      WORDPRESS_DB_USER: "{{ db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ db_password }}"
      WORDPRESS_DB_NAME: "{{ db_name }}"
    volumes:
      - "{{ wp_volume_path }}:/var/www/html"