---
- name: Create temporary directory
  file:
    path: "/tmp/ssl-{{ wp_domain }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false

- name: Create OpenSSL private key
  openssl_privatekey:
    path: "/tmp/ssl-{{ wp_domain }}/tls.key"
    size: 2048
  delegate_to: localhost
  become: false

- name: Create OpenSSL CSR
  openssl_csr:
    path: "/tmp/ssl-{{ wp_domain }}/tls.csr"
    privatekey_path: "/tmp/ssl-{{ wp_domain }}/tls.key"
    common_name: "{{ wp_domain }}"
  delegate_to: localhost
  become: false

- name: Create self-signed certificate
  openssl_certificate:
    path: "/tmp/ssl-{{ wp_domain }}/tls.crt"
    privatekey_path: "/tmp/ssl-{{ wp_domain }}/tls.key"
    csr_path: "/tmp/ssl-{{ wp_domain }}/tls.csr"
    provider: selfsigned
  delegate_to: localhost
  become: false

- name: Create Kubernetes TLS secret
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    namespace: "{{ wp_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: wordpress-tls
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ lookup('file', '/tmp/ssl-' + wp_domain + '/tls.crt') | b64encode }}"
        tls.key: "{{ lookup('file', '/tmp/ssl-' + wp_domain + '/tls.key') | b64encode }}"

- name: Clean up temporary certificate files
  file:
    path: "/tmp/ssl-{{ wp_domain }}"
    state: absent
  delegate_to: localhost
  become: false