---
all:
  children:
    wordpress:
      hosts:
        wp-prod:
          ansible_host: 35.181.234.232
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/test-aws-key-pair-new.pem
          ansible_python_interpreter: /usr/bin/python3