# ansible/inventory/hosts_prod.yml
---
all:
  children:
    prod:
      hosts:
        wordpress-prod:
          ansible_host: "{{ lookup('env', 'PROD_IP') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3