- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Enable Nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
  become: true

- name: Test Nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  become: true
  register: nginx_config_test
  changed_when: false
