---
system_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - python3-pip
  - acl
  - git
  - jq
  - tree
  - vim
  - nfs-common

python_packages:
  - boto3>=1.26.0
  - botocore>=1.29.0
  - kubernetes>=12.0.0
  - openshift

timezone: UTC
kubernetes_version: "1.28.4"