# ansible/roles/k3s/tasks/main.yml
---
- name: Download K3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0700'

- name: Install K3s
  shell: |
    export INSTALL_K3S_EXEC="server --tls-san {{ ansible_host }} --node-external-ip {{ ansible_host }}"
    /tmp/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s to be ready
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    state: present
    delay: 10
    timeout: 300

- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: Add nginx-ingress repository
  shell: |
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    helm repo update

- name: Install nginx-ingress
  shell: |
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
      --set controller.service.type=NodePort \
      --set controller.service.nodePorts.http=30080 \
      --set controller.service.nodePorts.https=30443
