---
- name: Fetch AWS Secrets
  command: "aws secretsmanager get-secret-value --secret-id book --region eu-west-3 --output json"
  register: secrets_result
  delegate_to: localhost
  become: false
  changed_when: false

- name: Set variables from secrets
  set_fact:
    aws_account_id: "{{ (secrets_result.stdout | from_json).SecretString | from_json | json_query('aws_account_id') }}"
    aws_ebs_csi_role_name: "{{ (secrets_result.stdout | from_json).SecretString | from_json | json_query('aws_ebs_csi_role_name') }}"

- name: Check if EBS CSI Driver is already installed
  command: helm list -n kube-system
  register: helm_list
  changed_when: false

- name: Delete old StorageClass if exists
  command: kubectl delete storageclass ebs-sc
  ignore_errors: true
  when: ebs_csi_enabled and "aws-ebs-csi-driver" not in helm_list.stdout

- name: Add Helm repo for EBS CSI Driver
  command: helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  become: false
  when: ebs_csi_enabled
  ignore_errors: true

- name: Update Helm repos
  command: helm repo update
  become: false
  when: ebs_csi_enabled
  changed_when: true

- name: Template EBS CSI values
  template:
    src: ebs-csi-values.yml.j2
    dest: /tmp/ebs-csi-values.yml
    mode: '0644'
  when: ebs_csi_enabled

- name: Install EBS CSI Driver
  command: >
    helm install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver 
    --namespace kube-system 
    --version {{ ebs_csi_version }}
    -f /tmp/ebs-csi-values.yml
  when: ebs_csi_enabled and "aws-ebs-csi-driver" not in helm_list.stdout

- name: Upgrade EBS CSI Driver if already installed
  command: >
    helm upgrade aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver 
    --namespace kube-system 
    --version {{ ebs_csi_version }}
    -f /tmp/ebs-csi-values.yml
  when: ebs_csi_enabled and "aws-ebs-csi-driver" in helm_list.stdout

- name: Clean up temporary values file
  file:
    path: /tmp/ebs-csi-values.yml
    state: absent
  when: ebs_csi_enabled