---
- name: Installer K3s
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" sh -s - --disable traefik
  args:
    executable: /bin/bash
  become: true

- name: S'assurer que kubectl est disponible
  copy:
    src: /usr/local/bin/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    remote_src: yes
  become: true
