---
- name: Déployer WordPress sur Kubernetes avec Helm
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Installer les packages python3-boto3 et python3-botocore
      apt:
        name:
          - python3-boto3
          - python3-botocore
        state: present
        update_cache: yes

    - name: Récupérer les secrets AWS via boto3
      set_fact:
        aws_secrets: "{{ lookup('amazon.aws.aws_secret', 'book', region='eu-west-3') }}"

    - name: Extraire les variables des secrets
      set_fact:
        wp_db_user: "{{ aws_secrets.MYSQL_USER }}"
        wp_db_password: "{{ aws_secrets.MYSQL_PASSWORD }}"
        wp_db_name: "{{ aws_secrets.MYSQL_DATABASE }}"

    - name: Créer un secret Kubernetes pour WordPress
      shell: |
        /usr/local/bin/kubectl delete secret wordpress-secrets -n default --ignore-not-found
        /usr/local/bin/kubectl create secret generic wordpress-secrets -n default \
          --from-literal=MYSQL_USER={{ wp_db_user }} \
          --from-literal=MYSQL_PASSWORD={{ wp_db_password }} \
          --from-literal=MYSQL_DATABASE={{ wp_db_name }}
      become_user: ubuntu
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    - name: Ajouter le repo Helm Bitnami
      command: helm repo add bitnami https://charts.bitnami.com/bitnami
      become_user: ubuntu
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    - name: Mettre à jour les dépôts Helm
      command: helm repo update
      become_user: ubuntu
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    - name: Déployer WordPress avec Helm
      become: true
      become_user: ubuntu
      become_flags: '-E'
      environment:
        KUBECONFIG: "/home/ubuntu/.kube/config"
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      shell: |
        helm upgrade --install wordpress bitnami/wordpress \
          --set mariadb.enabled=false \
          --set externalDatabase.host=wordpress-db.cdaookoquxxr.eu-west-3.rds.amazonaws.com \
          --set externalDatabase.user={{ wp_db_user }} \
          --set externalDatabase.password={{ wp_db_password }} \
          --set externalDatabase.database={{ wp_db_name }} \
          --set externalDatabase.port=3306 \
          --set service.type=LoadBalancer \
          --set wordpressHost=test.mmustar.fr

    - name: Vérifier que WordPress est bien déployé
      become: true
      become_user: ubuntu
      shell: /usr/local/bin/kubectl get pods -n default
      register: wordpress_pods
      changed_when: false
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    - name: Afficher les pods WordPress
      debug:
        msg: "{{ wordpress_pods.stdout_lines }}"
