---
- name: Download k3s
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Install k3s
  shell: INSTALL_K3S_VERSION={{ k3s_version }} /tmp/k3s-install.sh --write-kubeconfig-mode 644 {{ k3s_server_args }}
  args:
    creates: /usr/local/bin/k3s
  environment:
    INSTALL_K3S_EXEC: "{{ k3s_server_args }}"

- name: Wait for k3s to be ready
  wait_for:
    path: "{{ kubeconfig }}"
    delay: 10
    timeout: 300

- name: Wait for k3s node to be ready
  kubernetes.core.k8s_info:
    kind: Node
    name: "{{ ansible_hostname }}"
    kubeconfig: "{{ kubeconfig }}"
  register: node_status
  until: node_status.resources[0].status.conditions | selectattr('type', 'equalto', 'Ready') | selectattr('status', 'equalto', 'True') | list | count > 0
  retries: 30
  delay: 10

- name: Install NGINX Ingress Controller
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
