- name: Télécharger et installer K3s
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s
  become: true

- name: Attendre que K3s soit prêt
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    state: present
    timeout: 60
  become: true

- name: Vérifier si kubectl est installé
  command: kubectl version --client
  register: kubectl_installed
  ignore_errors: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Installer kubectl si absent
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/
  args:
    creates: /usr/local/bin/kubectl
  when: kubectl_installed.rc != 0
  become: true

- name: Vérifier si Helm est installé
  command: helm version
  register: helm_installed
  ignore_errors: true

- name: Installer Helm si absent
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  when: helm_installed.rc != 0
  become: true

- name: Installer le CSI Driver Secrets Store
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/main/deploy/rbac-secretproviderclass.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/main/deploy/secrets-store-csi-driver.yaml
  register: csi_installation
  changed_when: "'created' in csi_installation.stdout or 'configured' in csi_installation.stdout"
  become: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
