---
- name: Download K3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0700'

- name: Install K3s
  shell:
    cmd: INSTALL_K3S_VERSION={{ k3s_version }} /tmp/k3s-install.sh {{ k3s_server_args }}
  args:
    creates: /usr/local/bin/k3s

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Wait for node to be ready
  shell: kubectl wait --for=condition=Ready node/{{ inventory_hostname }} --timeout=300s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: node_ready
  until: node_ready.rc == 0
  retries: 30
  delay: 10

- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Create .kube directory
  file:
    path: ~/.kube
    state: directory
    mode: '0755'

- name: Copy kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    remote_src: yes
    mode: '0600'

- name: Add Bitnami Helm repository
  shell: helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo update