---
- name: Install AWS CLI dependencies
  apt:
    name:
      - python3-pip
      - python3-boto3
    state: present
    update_cache: yes

- name: Fetch AWS secrets info
  community.aws.aws_secretsmanager_info:
    names:
      - book
    region: "{{ aws_region }}"
  register: wp_secrets_info
  delegate_to: localhost
  become: false
  # no_log: true  # Décommentez cette ligne une fois le débogage terminé pour protéger les informations sensibles.

- name: Set fact with secrets
  set_fact:
    mysql_host: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).MYSQL_HOST }}"
    mysql_user: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).MYSQL_USER }}"
    mysql_password: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).MYSQL_PASSWORD }}"
    mysql_database: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).MYSQL_DATABASE }}"
    mysql_port: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).MYSQL_PORT }}"
    wp_auth_key: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).AUTH_KEY }}"
    wp_secure_auth_key: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).SECURE_AUTH_KEY }}"
    wp_logged_in_key: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).LOGGED_IN_KEY }}"
    wp_nonce_key: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).NONCE_KEY }}"
    wp_auth_salt: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).AUTH_SALT }}"
    wp_secure_auth_salt: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).SECURE_AUTH_SALT }}"
    wp_logged_in_salt: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).LOGGED_IN_SALT }}"
    wp_nonce_salt: "{{ (wp_secrets_info.secrets[0].SecretString | from_json).NONCE_SALT }}"
  no_log: true
