---
- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Démarrer et activer Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copier le fichier de configuration Nginx
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf
    mode: '0644'
  notify: Redémarrer Nginx

- name: Supprimer la configuration par défaut
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Redémarrer Nginx