# roles/nginx/tasks/main.yml
---
# Ajoutez ces tâches avant le reload
- name: Check nginx configuration
  command: nginx -t
  register: nginx_config_test
  changed_when: false
  ignore_errors: true

- name: Display nginx configuration test results
  debug:
    var: nginx_config_test

- name: Get nginx status
  command: systemctl status nginx
  register: nginx_status
  changed_when: false
  ignore_errors: true

- name: Display nginx status
  debug:
    var: nginx_status

- name: Check nginx logs
  command: journalctl -xeu nginx.service --no-pager
  register: nginx_logs
  changed_when: false
  ignore_errors: true

- name: Display nginx logs
  debug:
    var: nginx_logs

# Modifiez le handler reload pour inclure plus d'informations
- name: Reload Nginx
  block:
    - name: Try reload nginx
      service:
        name: nginx
        state: reloaded
  rescue:
    - name: Get detailed error information
      command: systemctl status nginx
      register: nginx_error_status
      ignore_errors: true

    - name: Display error information
      debug:
        var: nginx_error_status