---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Stop NGINX service
  service:
    name: nginx
    state: stopped

- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/nginx/ssl
    - /etc/nginx/conf.d
    - /var/www/html

- name: Copy NGINX main configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart nginx

- name: Copy WordPress virtual host configuration
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf
    mode: '0644'
  notify: restart nginx

- name: Remove default NGINX site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Enable NGINX service
  service:
    name: nginx
    state: started
    enabled: yes