grafana:
  ingress:
    tls:
      - secretName: "monitoring-tls"  # Même secret pour tous
        hosts:
          - grafana-monitoring.mmustar.fr

prometheus:
  ingress:
    tls:
      - secretName: "monitoring-tls"  # Même secret pour tous
        hosts:
          - prometheus-monitoring.mmustar.fr

alertmanager:
  ingress:
    tls:
      - secretName: "monitoring-tls"
        hosts:
          - alertmanager-monitoring.mmustar.fr

# Désactiver les composants inutiles
kubeEtcd: {enabled: false}
kubeControllerManager: {enabled: false}
kubeScheduler: {enabled: false}
kubeProxy: {enabled: false}