# Configuration globale Prometheus
global:
  evaluation_interval: 1m
  scrape_interval: 15s

prometheus:
  prometheusSpec:
    retention: 10d
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1000m

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - prometheus-monitoring.mmustar.fr
    tls:
      - secretName: monitoring-tls
        hosts:
          - prometheus-monitoring.mmustar.fr

# Configuration Alertmanager
alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - alertmanager-monitoring.mmustar.fr
    tls:
      - secretName: monitoring-tls
        hosts:
          - alertmanager-monitoring.mmustar.fr

  alertmanagerSpec:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

# Configuration Grafana
grafana:
  adminPassword: "admin"
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - grafana-monitoring.mmustar.fr
    tls:
      - secretName: monitoring-tls
        hosts:
          - grafana-monitoring.mmustar.fr

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/default

# Configurations Node Exporter
nodeExporter:
  enabled: true

# Configurations kube-state-metrics
kubeStateMetrics:
  enabled: true