- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Install Docker packages
  become: true
  apt:
    name:
      - docker-ce=5:20.10.24~3-0~ubuntu-focal
      - docker-ce-cli=5:20.10.24~3-0~ubuntu-focal
      - containerd.io=1.6.21-1
    state: present
    update_cache: yes

- name: Start and enable Docker service
  become: true
  service:
    name: docker
    state: started
    enabled: yes

- name: Add users to docker group
  become: true
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: Configure Docker daemon
  become: true
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m",
          "max-file": "3"
        }
      }
  notify: restart docker