---
collections:
  - name: community.general
  - name: community.kubernetes
  - name: kubernetes.core
  - name: community.aws
  - name: amazon.aws

roles:
  - name: geerlingguy.pip
  - name: geerlingguy.docker