hostNetwork: true
service:
  enabled: false
ports:
  web:
    port: 80
    protocol: TCP
  websecure:
    port: 443
    protocol: TCP
deployment:
  podSecurityContext:
    runAsUser: 65532
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532
    capabilities:
      add:
        - NET_BIND_SERVICE
logs:
  general:
    level: DEBUG
