# .github/workflows/code-quality.yml
name: Code Quality

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint yamllint

      - name: Lint Ansible
        run: |
          ansible-lint ansible/**/*.yml
          yamllint ansible/

      - name: Terraform Format Check
        uses: hashicorp/setup-terraform@v3
        
      - name: Check Terraform formatting
        run: |
          terraform fmt -check -recursive environments/