name: Deploy Monitoring Stack

on:
  push:
    branches: [mono]
  workflow_dispatch:

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config

      - name: Create certificate files
        run: |
          # Créer les fichiers de certificat et clé
          echo "${{ secrets.CERTIF_MONO }}" > mono.crt
          echo "${{ secrets.KEY_MONO }}" > mono.key

      - name: Transfer files
        run: |
          scp -i ~/.ssh/id_rsa scripts/prometheus-values.yaml ubuntu@${{ secrets.EC2_IP_MONOV }}:/home/ubuntu/
          scp -i ~/.ssh/id_rsa mono.crt ubuntu@${{ secrets.EC2_IP_MONOV }}:/home/ubuntu/
          scp -i ~/.ssh/id_rsa mono.key ubuntu@${{ secrets.EC2_IP_MONOV }}:/home/ubuntu/
          scp -i ~/.ssh/id_rsa scripts/deploy_mono.sh ubuntu@${{ secrets.EC2_IP_MONOV }}:/home/ubuntu/

      - name: Execute deployment
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP_MONOV }} "chmod +x /home/ubuntu/deploy_mono.sh && sudo -E /home/ubuntu/deploy_mono.sh"

      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa
          rm -f mono.crt mono.key