# ansible/roles/k3s/tasks/main.yml
---
 - name: Install required packages
   apt:
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present
      update_cache: yes
  
 - name: Download K3s install script
   get_url:
      url: https://get.k3s.io
      dest: /tmp/k3s-install.sh
      mode: '0755'
  
 - name: Install K3s
   shell: |
      INSTALL_K3S_EXEC="server \
        --disable traefik \
        --disable servicelb \
        --tls-san {{ inventory_hostname }} \
        --write-kubeconfig-mode 644 \
        --node-name {{ inventory_hostname }}" \
      sh /tmp/k3s-install.sh
   args:
      creates: /usr/local/bin/k3s
  
 - name: Wait for node to be ready
   shell: kubectl wait --for=condition=Ready nodes --all --timeout=300s
   changed_when: false
  
 - name: Install Helm
   shell: |
      curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
   args:
      creates: /usr/local/bin/helm
  
 - name: Add nginx-ingress repository
   shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  
 - name: Install nginx-ingress
       shell: |
      helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
        --namespace ingress-nginx \
        --create-namespace \
        --set controller.service.type=NodePort \
        --set controller.service.nodePorts.http=30080 \
        --set controller.service.nodePorts.https=30443